name: CI
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests 🧪
        uses: cypress-io/github-action@v2.9.7
        with:
          command: npm t
        env:
          AIO_API_KEY: ${{ secrets.AIO_API_KEY }}
        
      - name: Run hosted tests
        uses: cypress-io/github-action@v2.9.7
        with:
          config-file: cypress_hosted.json
        env:
          JIRA_PAT: ${{ secrets.JIRA_PAT }}
          
      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v2
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
